services:
  h2db:
    image: oscarfonts/h2:latest
    container_name: h2db
    ports:
      - "1521:1521"   # puerto TCP
      - "81:81"       # consola web
    environment:
      H2_OPTIONS: '-tcp -tcpAllowOthers -web -webAllowOthers -ifNotExists'
    volumes:
      - ./data/h2:/opt/h2-data
  app:
    build: .
    depends_on:
      - h2db
    environment:
      # Nombres genéricos y limpios
      DB_URL: jdbc:h2:tcp://h2db:1521//opt/h2-data/test
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    ports:
      - "8080:8080"